version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: '${DATABASE_URL}'
      API_HOST: '${API_HOST}'
      API_PORT: '${API_PORT}'
      APP_TOKEN_NAME: '${APP_TOKEN_NAME}'
      APP_TOKEN_KEY: '${APP_TOKEN_KEY}'
      APP_TOKEN_EXPIRE: '${APP_TOKEN_EXPIRE}'
    depends_on:
      - db

volumes:
  db-data: